import NavbarSideCompact from '@/components/layout/navbars/navbar-side-compact'
import NavbarSideFull from '@/components/layout/navbars/navbar-side-full'
import NavbarTop from '@/components/layout/navbars/navbar-top'
import BackToTop from '@/components/utils/back-to-top'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Pet Forum',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en' className='text-[12px] xs:text-[14px] sm:text-[16px]'>
            <body className={inter.className}>
                <main className='mx-auto md:w-5/6 max-w-6xl flex flex-col sm:flex-row'>
                    <div className='sm:hidden sticky top-0 z-20 bg-gray-900'><NavbarTop/></div>
                    <section className='flex-col place-content-between h-screen sticky top-0 z-10 hidden sm:flex'>
                        <div className='hidden sm:max-lg:block h-full'><NavbarSideCompact/></div>
                        <div className='hidden lg:block pe-2 h-full'><NavbarSideFull/></div>
                    </section>
                    <section className='grow sm:border-s md:border-e border-zinc-700 min-h-screen'>{children}</section>
                    <BackToTop/>
                </main>
            </body>
        </html>
    );
}
