import LoginPanel from '@/components/login-panel';
import NavbarSideCompact from '@/components/navbars/navbar-side-compact';
import NavbarSideFull from '@/components/navbars/navbar-side-full';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Pet Forum',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en' className='text-[12px] xs:text-[14px] sm:text-[16px]'>
            <body className={inter.className}>
                <main className='mx-auto md:w-5/6 max-w-6xl flex'>
                    <section className='flex flex-col place-content-between h-screen sticky top-0 z-10'>
                        <NavbarSideCompact></NavbarSideCompact>
                        <NavbarSideFull></NavbarSideFull>
                        <LoginPanel/>
                    </section>
                    <section className='grow sm:border-s md:border-e border-zinc-700 min-h-screen'>{children}</section>
                </main>
            </body>
        </html>
    );
}
